apiVersion: v1
data:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIC9zCCAd+gAwIBAgIJAOe6JT866ueYMA0GCSqGSIb3DQEBCwUAMBIxEDAOBgNV
    BAMMB2t1YmUtY2EwHhcNMTgxMDA0MTI1MTEwWhcNMjEwNjMwMTI1MTEwWjASMRAw
    DgYDVQQDDAdrdWJlLWNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
    3bJbIk9adHAsf6qHLlyT2GFnkbTXBl1cLGin4M7jrrfwpRUb88vKZ23VzRTuiiFQ
    78wkIa1hwLi+iGRpvqKdSnqr4iH3mlUWIfMIBiDeO63puWyF8CKc+hAFBtFeOxGW
    TT5OXlkKYYSTdHVo7GP4K9RUS6h7VIGwCBaI5EHgXRgYjBIZMQbvMOn6g4ZxZ8KZ
    kbrPnjpouPhZ6bn+6ca9vijPca3g+V86tisG0kKy8qNQsOwITTKPebMuz9lk7Ig9
    9HbXPBvxoFieg2mvrPcYlsb1/0Ux984Nbh3i8NmOQ98XWXyqAS344Rh58WHXHNVj
    8/7ZbUMNyKWzRieP+bTVTQIDAQABo1AwTjAdBgNVHQ4EFgQUjD3HJ/mIPUCSixKA
    JRjRx7oK5Q8wHwYDVR0jBBgwFoAUjD3HJ/mIPUCSixKAJRjRx7oK5Q8wDAYDVR0T
    BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAhRYcaRry4A8AWdfZKayPlDSnBLfk
    ld9ojDHqN35bI5joG4nEKoq9ptR9RYRIAn49jZDh8pYiA85SfnVH4qVSYsj8BjnA
    MKu3TeXdiX0lxN3VZSPkdk7W9GIcIooZ/R7RddvSaMZRmX1E566tq7J5HpZtfufY
    qtZjuDYrhVupdUzqYWBwSrICzuFiwAn456+TEWuNG1EFJupYvqnoQSmRqjSjfhoF
    9AUqZ8SvWSpeEWBK4NwBHFTi7TnU8wJcgUvKSRhspCQyvbNkfeNgKCF+sa8gnMWe
    C7h5DCgozzFhP43bpafyUoY+kc0/ISCG5aFpv89NoDRyzGcS3U2ARSCEyQ==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ca
  selfLink: /api/v1/namespaces/auth/configmaps/ca
